# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wcA.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1236, 648)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/wordcloud/wc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout1 = QtWidgets.QGridLayout()
        self.gridLayout1.setObjectName("gridLayout1")
        self.saveCLoudName = QtWidgets.QLineEdit(self.centralwidget)
        self.saveCLoudName.setObjectName("saveCLoudName")
        self.gridLayout1.addWidget(self.saveCLoudName, 3, 2, 1, 1)
        self.makeCloud = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeCloud.sizePolicy().hasHeightForWidth())
        self.makeCloud.setSizePolicy(sizePolicy)
        self.makeCloud.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.makeCloud.setObjectName("makeCloud")
        self.gridLayout1.addWidget(self.makeCloud, 3, 0, 1, 1)
        self.saveCloud = QtWidgets.QPushButton(self.centralwidget)
        self.saveCloud.setObjectName("saveCloud")
        self.gridLayout1.addWidget(self.saveCloud, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout1.addItem(spacerItem, 3, 3, 1, 1)
        self.textInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textInput.setMaximumSize(QtCore.QSize(10000, 400))
        self.textInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textInput.setObjectName("textInput")
        self.gridLayout1.addWidget(self.textInput, 1, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout1.addWidget(self.label, 0, 0, 1, 4)
        self.gridLayout_7.addLayout(self.gridLayout1, 0, 0, 1, 1)
        self.gridLayout2 = QtWidgets.QGridLayout()
        self.gridLayout2.setObjectName("gridLayout2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stopWordList = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopWordList.sizePolicy().hasHeightForWidth())
        self.stopWordList.setSizePolicy(sizePolicy)
        self.stopWordList.setMaximumSize(QtCore.QSize(180, 16777215))
        self.stopWordList.setObjectName("stopWordList")
        self.gridLayout_4.addWidget(self.stopWordList, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stopWordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.stopWordInput.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopWordInput.sizePolicy().hasHeightForWidth())
        self.stopWordInput.setSizePolicy(sizePolicy)
        self.stopWordInput.setObjectName("stopWordInput")
        self.gridLayout_3.addWidget(self.stopWordInput, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.addStopWord = QtWidgets.QPushButton(self.centralwidget)
        self.addStopWord.setObjectName("addStopWord")
        self.gridLayout_3.addWidget(self.addStopWord, 1, 1, 1, 1)
        self.deleteStopWord = QtWidgets.QPushButton(self.centralwidget)
        self.deleteStopWord.setObjectName("deleteStopWord")
        self.gridLayout_3.addWidget(self.deleteStopWord, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout2.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout2, 0, 1, 1, 1)
        self.gridLayout3 = QtWidgets.QGridLayout()
        self.gridLayout3.setObjectName("gridLayout3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout3.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(74, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout3.addItem(spacerItem3, 4, 0, 1, 1)
        self.trigramRB = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trigramRB.setFont(font)
        self.trigramRB.setObjectName("trigramRB")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.trigramRB)
        self.gridLayout3.addWidget(self.trigramRB, 3, 0, 1, 1)
        self.bigramRB = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bigramRB.setFont(font)
        self.bigramRB.setObjectName("bigramRB")
        self.buttonGroup.addButton(self.bigramRB)
        self.gridLayout3.addWidget(self.bigramRB, 2, 0, 1, 1)
        self.unigramRB = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unigramRB.sizePolicy().hasHeightForWidth())
        self.unigramRB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unigramRB.setFont(font)
        self.unigramRB.setObjectName("unigramRB")
        self.buttonGroup.addButton(self.unigramRB)
        self.gridLayout3.addWidget(self.unigramRB, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout3, 0, 2, 1, 1)
        self.gridLayout4 = QtWidgets.QGridLayout()
        self.gridLayout4.setObjectName("gridLayout4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout4.addWidget(self.label_4, 0, 0, 1, 1)
        self.rectangularRB = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rectangularRB.setFont(font)
        self.rectangularRB.setObjectName("rectangularRB")
        self.gridLayout4.addWidget(self.rectangularRB, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(117, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout4.addItem(spacerItem4, 3, 0, 1, 1)
        self.circularRB = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.circularRB.setFont(font)
        self.circularRB.setObjectName("circularRB")
        self.gridLayout4.addWidget(self.circularRB, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout4, 0, 3, 1, 1)
        self.mpl = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.gridLayout_7.addWidget(self.mpl, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1236, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WordCloudGenerator"))
        self.makeCloud.setText(_translate("MainWindow", "Make Word Cloud"))
        self.saveCloud.setText(_translate("MainWindow", "Save Cloud"))
        self.label.setText(_translate("MainWindow", "Paste your text here :-"))
        self.label_3.setText(_translate("MainWindow", "stop words"))
        self.addStopWord.setText(_translate("MainWindow", "Add"))
        self.deleteStopWord.setText(_translate("MainWindow", "Delete"))
        self.label_2.setText(_translate("MainWindow", "Type "))
        self.trigramRB.setText(_translate("MainWindow", "Trigrams"))
        self.bigramRB.setText(_translate("MainWindow", "Bigram"))
        self.unigramRB.setText(_translate("MainWindow", "Unigram"))
        self.label_4.setText(_translate("MainWindow", "Layout Type"))
        self.rectangularRB.setText(_translate("MainWindow", "Rectangular"))
        self.circularRB.setText(_translate("MainWindow", "Circular"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

from mplwidget import MplWidget
#import Icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

